# Generated by Django 4.0 on 2021-12-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nom Poble')),
                ('allName', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nom Complet Poble')),
                ('descargar', models.FileField(blank=True, null=True, upload_to='', verbose_name='PDF Ruta')),
                ('route', models.TextField(blank=True, max_length=500, null=True, verbose_name='Ruta')),
            ],
            options={
                'verbose_name': 'nom',
                'verbose_name_plural': 'noms',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Títol')),
                ('start', models.CharField(blank=True, default='2021-12-11T22:30:00', max_length=20, null=True, verbose_name='Data Inici')),
                ('end', models.CharField(blank=True, default='2021-12-11T22:30:00', max_length=20, null=True, verbose_name='Data Final')),
            ],
            options={
                'verbose_name': 'esdeveniment',
                'verbose_name_plural': 'esdeveniments',
            },
        ),
    ]
