# Generated by Django 4.0 on 2021-12-13 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MapApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cities',
            options={'verbose_name': 'ciutat', 'verbose_name_plural': 'ciutats'},
        ),
    ]
