# Generated by Django 4.0 on 2021-12-14 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MapApp', '0002_alter_cities_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='citie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MapApp.cities', verbose_name='Ciudad'),
        ),
    ]
